### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by alagaro** [jackee777/babelnetpy#3]
Hello, is the interface able to use other languages like Spanish?, I am trying to get synsets for the word "correr" and i get as a result traductions in english of the synonyms of that word.

from pybabelnet.babelnet import BabelNet

bn = BabelNet(open("llavebabel.txt", "r").read()) # or BabelNet("your API key")
Ids = bn.getSynset_Ids("correr", "ES")
print(Ids[8])

synsets = bn.getSynsets(Ids[8].id)
print(synsets[0].senses)

**Comment by jackee777** [comment]
Thank  you for your comments.

Now code doesn't work against other languages.
I forgot to add the targetLang option:
 https://babelnet.io/v5/getSynset?id=bn:00084451v&targetLang=ES&key=<your_key>

I will modify the code to other languages from now. It will be finished by tommorrow.

P.S. I may rename this directory again because pybabelnet is the same as https://github.com/alvations/pyBabelNet 
(Unfortunatelly, I don't know how to use this).

**Comment by alagaro** [comment]
Thank you for the quick answer, I've changed that missing parameter in the function of the class and it works now.

**Comment by alagaro** [comment]
Thank you for the quick answer, I understand now
